version: '2.1'
services:
  consul:
    image: autopilotpattern/consul:0.7.3r39
    restart: always
    dns:
      - 127.0.0.1
    labels:
      - triton.cns.services=consul
    ports:
      - "8500:8500"
    command: >
      /usr/local/bin/containerpilot
    environment:
      - CONSUL_DEV=1
  nats:
      image: autopilotpattern/nats:0.9.6-r1.0.0
      restart: always
      ports:
        - 8222
      links:
        - consul:consul
      environment:
        - CONSUL=consul
        - CONSUL_AGENT=1
        - NATS_USER=ruser
        - NATS_PASSWORD=password
  redis:
      image: redis
      expose:
        - 6379
      restart: always
  gateway:
      build: ./gateway
      ports:
        - "8080:8080"
      links:
        - consul:consul
        - redis:redis
      environment:
        - CONSUL=consul
      restart: always
      dns:
        - 127.0.0.1
  influxdb:
    image: autopilotpattern/influxdb:1.1.1
    ports:
      - "8086:8086"
      - "8083:8083"
    restart: always
    links:
      - consul:consul
    environment:
      - CONSUL=consul
      - ADMIN_USER=root
      - INFLUXDB_INIT_PWD=root123
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_REPORTING_DISABLED=true
      - INFLUXDB_DATA_QUERY_LOG_ENABLED=false
      - INFLUXDB_HTTP_LOG_ENABLED=false
      - INFLUXDB_CONTINUOUS_QUERIES_LOG_ENABLED=false
  serializer:
    build: ./serializer
    links:
      - consul:consul
    environment:
      - PORT=10000
      - CONSUL=consul
      - INFLUXDB_USER=root
      - INFLUXDB_PWD=root123
    expose:
      - 10000
    restart: always
  frontend:
    build: ./frontend
    links:
      - consul:consul
    environment:
      - CONSUL=consul
      - PORT=8080
    expose:
      - 8080
    restart: always
  smartthings:
    build: ./smartthings
    links:
      - consul:consul
    expose:
      - 8080
    environment:
      - PORT=8080
      - CONSUL=consul
      - NATS_USER=ruser
      - NATS_PASSWORD=password
      - FAKE_MODE=true
    restart: always
  temperature:
    build: ./sensor
    links:
      - consul:consul
    environment:
      - SENSOR_TYPE=temperature
      - CONSUL=consul
      - NATS_USER=ruser
      - NATS_PASSWORD=password
    restart: always
