version: '2.1'
services:
  consul:
    image: autopilotpattern/consul:0.7.3r39
    restart: always
    dns:
      - 127.0.0.1
    labels:
      - triton.cns.services=consul
    ports:
      - "8500:8500"
    command: >
      /usr/local/bin/containerpilot
    environment:
      - CONSUL_DEV=1
  redis:
      image: redis
      expose:
        - 6379
      restart: always
  gateway:
      build: ./gateway
      ports:
        - "8080:8080"
      links:
        - consul:consul
        - redis:redis
      environment:
        - CONSUL=consul
      restart: always
      dns:
        - 127.0.0.1
  frontend:
    build: ./frontend
    links:
      - consul:consul
    environment:
      - CONSUL=consul
      - PORT=8080
    expose:
      - 8080
    restart: always
